//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPickerProject.DBTarget
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataUrun()
        {
            this.DataUrunFiyatTarihce = new HashSet<DataUrunFiyatTarihce>();
            this.DataUrunKategori = new HashSet<DataUrunKategori>();
            this.DataUrunResim = new HashSet<DataUrunResim>();
        }
    
        public int DataUrunID { get; set; }
        public int WebSiteID { get; set; }
        public int BrandID { get; set; }
        public string OriginalID { get; set; }
        public string Name { get; set; }
        public string SKU { get; set; }
        public decimal OldPrice { get; set; }
        public decimal Price { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DataMarka DataMarka { get; set; }
        public virtual WebSite WebSite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataUrunFiyatTarihce> DataUrunFiyatTarihce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataUrunKategori> DataUrunKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataUrunResim> DataUrunResim { get; set; }
    }
}
