//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPickerProject.DBTarget
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataUrunResim
    {
        public int DataUrunResimID { get; set; }
        public int ProductID { get; set; }
        public string ImagePath { get; set; }
        public string OriginalImagePath { get; set; }
        public int OrderNumber { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DataUrun DataUrun { get; set; }
    }
}
