//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPickerProject.DBTarget
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTargetEntities : DbContext
    {
        public DBTargetEntities()
            : base("name=DBTargetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Nitelik> Nitelik { get; set; }
        public virtual DbSet<UrunKategori> UrunKategori { get; set; }
        public virtual DbSet<UrunNitelik> UrunNitelik { get; set; }
        public virtual DbSet<UrunResim> UrunResim { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<Marka> Marka { get; set; }
        public virtual DbSet<DataHataLog> DataHataLog { get; set; }
        public virtual DbSet<DataKategori> DataKategori { get; set; }
        public virtual DbSet<DataMarka> DataMarka { get; set; }
        public virtual DbSet<DataUrun> DataUrun { get; set; }
        public virtual DbSet<DataUrunFiyatTarihce> DataUrunFiyatTarihce { get; set; }
        public virtual DbSet<DataUrunKategori> DataUrunKategori { get; set; }
        public virtual DbSet<DataUrunLink> DataUrunLink { get; set; }
        public virtual DbSet<DataUrunResim> DataUrunResim { get; set; }
        public virtual DbSet<WebSite> WebSite { get; set; }
    }
}
