//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPickerProject.DBTarget
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.UrunKategori = new HashSet<UrunKategori>();
            this.UrunNitelik = new HashSet<UrunNitelik>();
            this.UrunResim = new HashSet<UrunResim>();
        }
    
        public int UrunId { get; set; }
        public string OriginalId { get; set; }
        public int MarkaId { get; set; }
        public Nullable<int> WebSiteId { get; set; }
        public string Sku { get; set; }
        public string UrunAdi { get; set; }
        public string KisaAciklama { get; set; }
        public string Aciklama { get; set; }
        public decimal Fiyat { get; set; }
        public string Etiketler { get; set; }
        public string AdresUrl { get; set; }
        public bool AnasayfadaGoster { get; set; }
        public int GoruntulenmeSayisi { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTitle { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public Nullable<System.DateTime> GuncellemeTarih { get; set; }
        public int Sira { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunKategori> UrunKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunNitelik> UrunNitelik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunResim> UrunResim { get; set; }
        public virtual Marka Marka { get; set; }
    }
}
