//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPickerProject.DBTarget
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebSite()
        {
            this.DataHataLog = new HashSet<DataHataLog>();
            this.DataKategori = new HashSet<DataKategori>();
            this.DataMarka = new HashSet<DataMarka>();
            this.DataUrun = new HashSet<DataUrun>();
            this.DataUrunLink = new HashSet<DataUrunLink>();
            this.Marka = new HashSet<Marka>();
        }
    
        public int WebSiteId { get; set; }
        public string WebSiteAdi { get; set; }
        public string SiteUrl { get; set; }
        public string ResimYolu { get; set; }
        public byte[] Resim { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public Nullable<System.DateTime> GuncellemeTarih { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataHataLog> DataHataLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataKategori> DataKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataMarka> DataMarka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataUrun> DataUrun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataUrunLink> DataUrunLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marka> Marka { get; set; }
    }
}
